### ISSUE TITLE
D3.js not installed

### ISSUE THREAD

**Issue by KulikDM** [mljar/supertree#11]
Hi,

Another issue I ran into was with the `show_tree()` function while using a Jupyter Notebook in VSCode.

The error resulted in a blank canvas being rendered with the error message that D3.js was not installed and the blank canvas just kept extending until I restarted the kernel.

Not sure what went wrong, but specs are same as before and also using the latest VSCode.

**Comment by KulikDM** [comment]
@Marchlak unfortunately the error persisted ever after restarting the kernel. Hope it's a simple fix and more than happy to test and provide feedback.

**Comment by Thornam** [comment]
I experience the same issue.

The library seems really nice, so hope this will be fixed.

**Comment by Marchlak** [comment]
Hi, the latest version of Supertree should finally work in VS Code. However, since the notebook in VS Code differs from browser-based notebooks, if any issues arise, such as incorrect sizing or visibility of an element, please create an issue. At the moment, the modal window does not work in VS Code, but this option will be available in the next version only where it was originally intended, which is in Jupyter Notebook, where sometimes the output cell is small. For those who encounter this issue and have trouble importing D3 in VS Code, download, load, and invoke the d3.js file by IPython, changing the line from:
```
! function(t, n) {
    "object" == typeof exports && "undefined" != typeof module ? n(exports) : "function" == typeof define && define.amd ? define(["exports"], n) : n((t = "undefined" != typeof globalThis ? globalThis : t || self).d3 = t.d3 || {})
}(this, (function(t) {
    "use strict";
 ```
 to
 ```
  !function(t, n) {
    n((t = "undefined" != typeof globalThis ? globalThis : t || self).d3 = t.d3 || {})
}(this, (function(t) {
    "use strict";
    ```
    Also, the resizing of the div is handled by the CSS rule height: 100vh.
